/**
 * The Manzel identity ("Taq", 2026-09-30), from its source files to the site.
 *
 * Source: assets/brand/*.svg — the designer's files (the app repo has the same
 * copies, with its own scripts/brand.mjs). In the lockups منزل and manzel are
 * one size (rebalanced 2026-10-10; see the app's scripts/brand.mjs). Change the
 * identity there, then:
 *
 *   node scripts/brand.mts          the shapes and the favicon
 *   node scripts/generate-images.mts   the icons and social cards, from them
 *
 * Writes:
 *   components/brand/paths.ts   the shapes, for LogoMark and Logo
 *   app/icon.svg                the favicon: the arch-m on its lapis tile
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const brand = join(root, 'assets', 'brand');
const SAFFRON = '#F0BE51';

interface Piece { d: string; light: boolean }

function paths(file: string): Piece[] {
  const svg = readFileSync(join(brand, file), 'utf8');
  return [...svg.matchAll(/<path\b([^>]*)>/g)].map((match) => {
    const attrs = match[1];
    const fill = /\bfill="(#[0-9A-Fa-f]{6})"/.exec(attrs)?.[1]?.toUpperCase() ?? '';
    const d = /\bd="([^"]+)"/.exec(attrs)?.[1] ?? '';
    return { d, light: fill === SAFFRON };
  });
}

function bounds(ds: string[]) {
  let x0 = Infinity; let y0 = Infinity; let x1 = -Infinity; let y1 = -Infinity;
  for (const d of ds) {
    const nums = (d.match(/-?\d+(\.\d+)?/g) ?? []).map(Number);
    for (let i = 0; i + 1 < nums.length; i += 2) {
      x0 = Math.min(x0, nums[i]); x1 = Math.max(x1, nums[i]);
      y0 = Math.min(y0, nums[i + 1]); y1 = Math.max(y1, nums[i + 1]);
    }
  }
  const r = (v: number) => Math.round(v * 100) / 100;
  return { x: r(x0), y: r(y0), w: r(x1 - x0), h: r(y1 - y0) };
}

function group(list: Piece[]) {
  const b = bounds(list.map((piece) => piece.d));
  return {
    viewBox: `${b.x} ${b.y} ${b.w} ${b.h}`,
    width: b.w,
    height: b.h,
    letters: list.filter((piece) => !piece.light).map((piece) => piece.d),
    light: list.filter((piece) => piece.light).map((piece) => piece.d),
  };
}

const mark = group(paths('manzel-taq-appicon.svg'));
const stacked = paths('manzel-taq-lockup-paper.svg');
const dari = group(stacked.slice(0, 6));
const latin = group(stacked.slice(6));
const lockup = group(stacked);
const horizontal = group(paths('manzel-taq-horizontal-paper.svg'));

if (mark.letters.length !== 1 || mark.light.length !== 1 || dari.light.length !== 1 || latin.light.length !== 1) {
  throw new Error('The brand files are not shaped as expected: check assets/brand/*.svg.');
}

const json = (value: unknown) => JSON.stringify(value, null, 2);

writeFileSync(join(root, 'components', 'brand', 'paths.ts'), `/**
 * GENERATED by scripts/brand.mts from assets/brand/*.svg — do not edit.
 *
 * The Manzel identity, "Taq" (طاق, the arch): the name's letters are drawn
 * as pointed Afghan arches, with a light on inside one of them. \`letters\`
 * take the ink colour (lapis on paper, paper on lapis); \`light\` is always
 * saffron. Draw them with LogoMark and Logo (./logo.tsx).
 */

export interface BrandShape {
  viewBox: string;
  width: number;
  height: number;
  letters: readonly string[];
  light: readonly string[];
}

export const BRAND = { lapis: '#1E4E8C', lapisBright: '#3467BD', paper: '#FBF8F3', saffron: '${SAFFRON}' } as const;

/** The arch-m: two neighbouring homes, one lit. The app icon's drawing. */
export const MARK: BrandShape = ${json(mark)};

/** The app icon's square: the arch-m sits on it at its own coordinates. */
export const TILE = { size: 100, radius: 22.5 } as const;

/** منزل, in the identity's Kufi, with the gold dot over the ن. */
export const WORDMARK_DARI: BrandShape = ${json(dari)};

/** manzel, the m and n drawn as arches, the light inside the n. */
export const WORDMARK_LATIN: BrandShape = ${json(latin)};

/** منزل over manzel. */
export const LOCKUP_STACKED: BrandShape = ${json(lockup)};

/** manzel منزل on one line. */
export const LOCKUP_HORIZONTAL: BrandShape = ${json(horizontal)};
`);
console.log('✓ components/brand/paths.ts');

writeFileSync(join(root, 'app', 'icon.svg'), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect width="100" height="100" rx="22.5" fill="#1E4E8C"/>
  <path fill-rule="evenodd" fill="#FBF8F3" d="${mark.letters[0]}"/>
  <path fill-rule="evenodd" fill="${SAFFRON}" d="${mark.light[0]}"/>
</svg>
`);
console.log('✓ app/icon.svg');
