/**
 * The Manzel identity, "Taq" (طاق, the arch) — the same drawing as the app
 * (components/ui/brand.tsx there), from the same designer's files.
 *
 * The name's own letters carry the architecture: the m and n of "manzel" are
 * pointed Afghan arches, the ن of منزل has a gold dot, and a light is on
 * inside the second arch — two neighbouring homes, somebody home in one.
 *
 *   LogoMark   the arch-m: on its lapis tile (the app icon), or alone
 *   Logo       the name: منزل, or "manzel منزل" on English pages
 *
 * Shapes: ./paths.ts, generated by scripts/brand.mts from assets/brand/*.svg.
 */

import { BRAND, LOCKUP_HORIZONTAL, MARK, TILE, WORDMARK_DARI, type BrandShape } from './paths';

function Shape({ shape, ink }: { shape: BrandShape; ink: string }) {
  return (
    <>
      {shape.letters.map((d, index) => <path key={`l${index}`} d={d} fill={ink} fillRule="evenodd" />)}
      {shape.light.map((d, index) => <path key={`g${index}`} d={d} fill={BRAND.saffron} fillRule="evenodd" />)}
    </>
  );
}

/**
 * The arch-m. `tile` (default) is the app icon: the arches in paper on a
 * rounded lapis square. `mark` is the arches alone — lapis, or paper with
 * `light` on a dark ground; `size` is then its width.
 */
export function LogoMark({
  size = 40,
  className,
  title,
  variant = 'tile',
  light = false,
}: {
  size?: number;
  className?: string;
  title?: string;
  variant?: 'tile' | 'mark';
  light?: boolean;
}) {
  const a11y = title ? { role: 'img' as const } : { 'aria-hidden': true as const };

  if (variant === 'mark') {
    return (
      <svg
        width={size}
        height={(size * MARK.height) / MARK.width}
        viewBox={MARK.viewBox}
        className={`${light ? 'text-[#FBF8F3]' : 'text-lapis-600 dark:text-lapis-300'} ${className ?? ''}`}
        {...a11y}
      >
        {title ? <title>{title}</title> : null}
        <Shape shape={MARK} ink="currentColor" />
      </svg>
    );
  }

  return (
    <svg width={size} height={size} viewBox={`0 0 ${TILE.size} ${TILE.size}`} className={className} {...a11y}>
      {title ? <title>{title}</title> : null}
      <rect width={TILE.size} height={TILE.size} rx={TILE.radius} fill={BRAND.lapis} />
      <Shape shape={MARK} ink={BRAND.paper} />
    </svg>
  );
}

/**
 * The name, as the header and footer show it. منزل on Dari and Pashto pages;
 * "manzel منزل" on English ones, where the Latin line leads. `size` is the
 * height of the Dari letters in pixels; `light` sets the letters in paper,
 * for the dark lapis and night bands.
 */
export function Logo({
  latin = false,
  size = 36,
  light = false,
}: {
  latin?: boolean;
  size?: number;
  /** On the dark lapis band, the letters are paper. */
  light?: boolean;
}) {
  const shape = latin ? LOCKUP_HORIZONTAL : WORDMARK_DARI;
  // The Dari letters are the full height of the Dari wordmark, and 300 of the
  // horizontal lockup's 300 units: one size setting reads the same either way.
  const height = size;
  const width = (height * shape.width) / shape.height;

  return (
    <svg
      width={Math.round(width)}
      height={height}
      viewBox={shape.viewBox}
      className={`inline-block shrink-0 ${light ? 'text-[#FBF8F3]' : 'text-lapis-600 dark:text-lapis-300'}`}
      role="img"
      aria-label="منزل Manzel"
    >
      <Shape shape={shape} ink="currentColor" />
    </svg>
  );
}
